### ISSUE TITLE
Let's instrument the site (if possible) to show a built preview of all PRs.

### ISSUE THREAD

**Issue by fperez** [UCB-stat-159-s23/site#3]
It would be great to add an action that does a full build of the site for any PRs. This way, one could more easily see the result of the changes in a real site rather than imagining what they look like from the sources, or having to do a local build.

This would be similar to what we do in many Jupyter projects (see an example [here in JupyterLab](https://github.com/jupyterlab/jupyterlab/pull/13895#issuecomment-1409532739)) where we automatically build a Binder link for anyone to be able to view the PR's effect without having to do a build.  

I haven't looked into how to do it, but I'm sure it's possible...

**Comment by facusapienza21** [comment]
That will be great! I was doing the build of the JupyterBook in local, but it's very inconvenient at the moment of checking how the new website looks like. I will explore this.

**Comment by facusapienza21** [comment]
Thank you @yuvipanda for his feedback on this. What we need is [Read the Docs](https://jupyterbook.org/en/stable/publish/readthedocs.html) for JupyteBook, which should create a different link where you can see the changes in the PR. I will add this to the repository to see if it works!

**Comment by facusapienza21** [comment]
I was exploring this but still wasn't able to make it work.

I was able to set up the readtodocs page following the [tutorial](https://docs.readthedocs.io/en/stable/tutorial/index.html). However, in order to readthedocs to work with a JupyterBook, an extra configuration step needs to be made, as it is explained in the [JupyterBook documentation](https://jupyterbook.org/en/stable/publish/readthedocs.html). This requieres the configuration of sphinx to work, which can be done with the [creation](https://jupyterbook.org/en/stable/sphinx/index.html#sphinx-convert) of the `conf.py` file: 
```
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      - "jupyter-book config sphinx ."

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py
   
   # Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: book-requirements.txt
```
However, this doesn't work when building the readthedocs

![Screen Shot 2023-02-02 at 7 56 23 PM](https://user-images.githubusercontent.com/39526081/216509131-3038a99a-f0a4-4332-ac3f-8b24f7c7fc1b.png)

I need to explore why it doesn't recognizes the `conf.py` file even when is there. 

Once this is working, it should be easy to integrate this with PR, as it is explined in the readthedocs documentation.
